steps:
    - name: 'gcr.io/cloud-builders/docker'
        args: ['build', '-t', 'gcr.io/ideia-back/ideia-backend:$SHORT_SHA', '-f', 'Dockerfile','.']  
    
    - name: 'docker'
        args: ['run', '-d', '--name', 'ideia-backend', 'gcr.io/ideia-back/ideia-backend:$SHORT_SHA']